-- =====================================================================
-- EASYSESH database update (for a database that already ran setup.sql)
--  • Fix: "You already have a studio" when saving a studio application again
--  • Contact support (tickets in the app, replies from the admin dashboard)
--  • Message requests (studios can write to artists; artists accept/decline)
--  • Support ratings (users rate closed support requests)
--  • Notification texts say EasySesh
--
-- Supabase → SQL Editor → New query → paste this whole file → Run.
-- Safe to run more than once; keeps all existing data.
-- Generated by supabase/scripts/build_update.py
-- =====================================================================

-- Studio save fix ------------------------------------------------------
create or replace function public.guard_studios()
returns trigger language plpgsql as $$
begin
  -- Keep the "from" price in sync with the session types.
  new.price_from := coalesce((select min((t.value ->> 'hourly_rate')::int) from jsonb_array_elements(new.session_types) as t), 0);

  if public.is_trusted() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    -- Upsert of an existing row: Postgres runs this INSERT trigger before resolving the conflict.
    -- The UPDATE branch below guards the row that actually gets written, so leave it alone here.
    if exists (select 1 from public.studios where id = new.id) then
      return new;
    end if;
    if new.owner_id is distinct from auth.uid()
       or not exists (select 1 from public.profiles where id = auth.uid() and role = 'studio_owner' and status = 'active') then
      raise exception 'forbidden' using errcode = '42501';
    end if;
    if exists (select 1 from public.studios where owner_id = auth.uid() and id <> new.id) then
      raise exception 'You already have a studio.';
    end if;
    new.status := 'draft';
    new.is_active := false;
    new.is_verified := false;
    new.admin_note := null;
    new.rating_average := 0;
    new.review_count := 0;
    new.booking_count := 0;
    new.submitted_at := null;
    new.reviewed_at := null;
    new.reviewed_by := null;
    new.created_at := now();
  else
    new.id := old.id;
    new.owner_id := old.owner_id;
    new.status := old.status;
    new.is_verified := old.is_verified;
    new.admin_note := old.admin_note;
    new.rating_average := old.rating_average;
    new.review_count := old.review_count;
    new.booking_count := old.booking_count;
    new.submitted_at := old.submitted_at;
    new.reviewed_at := old.reviewed_at;
    new.reviewed_by := old.reviewed_by;
    new.created_at := old.created_at;
    if new.status <> 'approved' then
      new.is_active := false;
    end if;
  end if;
  return new;
end;
$$;

-- Support --------------------------------------------------------------
-- EasySesh: in-app support. Users open tickets from the app, admins answer them in the admin dashboard.
-- Tables are read-only for clients; every write goes through the RPCs below.

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  subject text not null check (char_length(subject) between 3 and 120),
  category text not null default 'other'
    check (category in ('account', 'booking', 'payment', 'studio', 'bug', 'other')),
  booking_id uuid references public.bookings (id) on delete set null,
  -- open: waiting for EasySesh · answered: waiting for the user · closed: done
  status text not null default 'open' check (status in ('open', 'answered', 'closed')),
  user_unread integer not null default 0,
  admin_unread integer not null default 0,
  last_message_preview text not null default '',
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);
create index if not exists support_tickets_user_idx on public.support_tickets (user_id, last_message_at desc);
create index if not exists support_tickets_status_idx on public.support_tickets (status, last_message_at desc);

create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets (id) on delete cascade,
  sender_id uuid references public.profiles (id) on delete set null,
  from_admin boolean not null default false,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);
create index if not exists support_messages_ticket_idx on public.support_messages (ticket_id, created_at);

alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;
drop policy if exists "support_tickets: own or admin read" on public.support_tickets;
create policy "support_tickets: own or admin read" on public.support_tickets for select
  using (user_id = auth.uid() or public.is_admin());
drop policy if exists "support_messages: own or admin read" on public.support_messages;
create policy "support_messages: own or admin read" on public.support_messages for select
  using (public.is_admin() or exists (select 1 from public.support_tickets t where t.id = ticket_id and t.user_id = auth.uid()));

-- Admin inbox rows with who wrote in.
drop view if exists public.admin_support_tickets;
create view public.admin_support_tickets with (security_invoker = true) as
select t.*, p.email as user_email, p.role as user_role,
  coalesce(nullif(a.artist_name, ''), nullif(s.name, ''), p.email) as user_name,
  b.reference as booking_reference
from public.support_tickets t
join public.profiles p on p.id = t.user_id
left join public.artist_profiles a on a.id = t.user_id
left join public.studios s on s.owner_id = t.user_id
left join public.bookings b on b.id = t.booking_id;

-- Adds a message to a ticket and updates its status, counters and preview.
create or replace function public.add_support_message(p_ticket_id uuid, p_body text, p_from_admin boolean)
returns public.support_messages
language plpgsql security definer set search_path = public
as $$
declare
  t public.support_tickets;
  m public.support_messages;
  new_id uuid := gen_random_uuid();
  body text := btrim(coalesce(p_body, ''));
begin
  -- Plain assignments on purpose: the Supabase SQL Editor treats "select ... in-to var"
  -- as a new table and breaks the function when this file is pasted.
  perform 1 from public.support_tickets where id = p_ticket_id for update;
  t := (select x from public.support_tickets x where x.id = p_ticket_id);
  if t.id is null then raise exception 'not_found'; end if;
  if body = '' then raise exception 'Write a message first.'; end if;
  if char_length(body) > 4000 then raise exception 'Message is too long (max 4000 characters).'; end if;

  insert into public.support_messages (id, ticket_id, sender_id, from_admin, body)
  values (new_id, t.id, auth.uid(), p_from_admin, body);
  m := (select x from public.support_messages x where x.id = new_id);

  update public.support_tickets set
    status = case when p_from_admin then 'answered' else 'open' end,
    user_unread = case when p_from_admin then user_unread + 1 else 0 end,
    admin_unread = case when p_from_admin then 0 else admin_unread + 1 end,
    last_message_preview = left(body, 140),
    last_message_at = m.created_at,
    closed_at = null
  where id = t.id;

  if p_from_admin then
    perform public.notify(t.user_id, 'system', 'EasySesh support replied', t.subject || ': ' || left(body, 120));
  end if;
  return m;
end;
$$;
revoke execute on function public.add_support_message from public, anon, authenticated;

-- App: open a new ticket with its first message.
create or replace function public.create_support_ticket(p_subject text, p_category text, p_body text, p_booking_id uuid default null)
returns public.support_tickets
language plpgsql security definer set search_path = public
as $$
declare
  new_id uuid := gen_random_uuid();
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if p_booking_id is not null and not exists (
    select 1 from public.bookings b
    where b.id = p_booking_id and (b.artist_id = auth.uid() or public.owns_studio(b.studio_id))
  ) then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  -- Light spam protection.
  if (select count(*) from public.support_tickets where user_id = auth.uid() and status <> 'closed') >= 5 then
    raise exception 'You already have 5 open requests. Please continue in one of them.';
  end if;
  if (select count(*) from public.support_tickets where user_id = auth.uid() and created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Too many requests. Please try again later.';
  end if;

  insert into public.support_tickets (id, user_id, subject, category, booking_id)
  values (new_id, auth.uid(), btrim(coalesce(p_subject, '')), coalesce(nullif(p_category, ''), 'other'), p_booking_id);
  perform public.add_support_message(new_id, p_body, false);
  return (select x from public.support_tickets x where x.id = new_id);
end;
$$;

-- App (ticket owner) or admin dashboard: reply in a ticket.
create or replace function public.send_support_message(p_ticket_id uuid, p_body text)
returns public.support_messages
language plpgsql security definer set search_path = public
as $$
declare
  owner uuid;
begin
  owner := (select user_id from public.support_tickets where id = p_ticket_id);
  if owner is null then raise exception 'not_found'; end if;
  if public.is_admin() then
    return public.add_support_message(p_ticket_id, p_body, true);
  elsif owner = auth.uid() then
    return public.add_support_message(p_ticket_id, p_body, false);
  end if;
  raise exception 'forbidden' using errcode = '42501';
end;
$$;

-- Clears the unread counter for whoever is reading.
create or replace function public.mark_support_ticket_read(p_ticket_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if public.is_admin() then
    update public.support_tickets set admin_unread = 0 where id = p_ticket_id;
  else
    update public.support_tickets set user_unread = 0 where id = p_ticket_id and user_id = auth.uid();
  end if;
end;
$$;

-- The user can close their own ticket; admins can close or reopen any ticket.
create or replace function public.set_support_ticket_status(p_ticket_id uuid, p_status text)
returns public.support_tickets
language plpgsql security definer set search_path = public
as $$
declare
  t public.support_tickets;
begin
  if p_status not in ('open', 'answered', 'closed') then raise exception 'invalid status'; end if;
  perform 1 from public.support_tickets where id = p_ticket_id for update;
  t := (select x from public.support_tickets x where x.id = p_ticket_id);
  if t.id is null then raise exception 'not_found'; end if;
  if not public.is_admin() and not (t.user_id = auth.uid() and p_status = 'closed') then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  update public.support_tickets
  set status = p_status, closed_at = case when p_status = 'closed' then now() end
  where id = t.id;
  return (select x from public.support_tickets x where x.id = t.id);
end;
$$;

-- Admins see new support messages live.
do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'support_messages') then
    alter publication supabase_realtime add table public.support_messages;
  end if;
end $$;

-- Message requests -----------------------------------------------------
-- EasySesh: studios can start conversations with artists. A conversation a studio starts with an
-- artist it has no history with lands in the artist's "Requests" until the artist accepts it
-- (or replies). A declined request stays closed: the studio can't keep writing.

alter table public.conversations
  add column if not exists request_status text not null default 'accepted'
    check (request_status in ('accepted', 'pending', 'declined')),
  add column if not exists started_by_studio boolean not null default false,
  add column if not exists artist_avatar_url text;

-- Studios can't write in a conversation the artist declined.
drop policy if exists "messages: participants send" on public.messages;
create policy "messages: participants send" on public.messages for insert
  with check (
    sender_id = auth.uid() and kind = 'text' and public.is_active_user()
    and exists (
      select 1 from public.conversations c
      where c.id = conversation_id
        and (c.artist_id = auth.uid()
             or (public.owns_approved_studio(c.studio_id) and c.request_status <> 'declined'))
    )
  );

-- Artists a studio can message: search by name for studio owners with an approved studio.
create or replace function public.search_artists(p_query text)
returns table (id uuid, artist_name text, city text, genres text[], avatar_url text, is_verified boolean, has_booked boolean)
language plpgsql stable security definer set search_path = public
as $$
declare
  q text := btrim(coalesce(p_query, ''));
  my_studio uuid := (select s.id from public.studios s where s.owner_id = auth.uid() limit 1);
begin
  if my_studio is null or not public.owns_approved_studio(my_studio) then
    raise exception 'Only approved studios can message artists.' using errcode = '42501';
  end if;
  return query
    select a.id, a.artist_name, a.city, a.genres, a.avatar_url, a.is_verified,
      exists (select 1 from public.bookings b where b.artist_id = a.id and b.studio_id = my_studio) as has_booked
    from public.artist_profiles a
    join public.profiles p on p.id = a.id
    where p.status = 'active' and p.role = 'artist' and a.artist_name <> ''
      and (char_length(q) < 2 and exists (select 1 from public.bookings b where b.artist_id = a.id and b.studio_id = my_studio)
           or char_length(q) >= 2 and (a.artist_name ilike '%' || q || '%' or a.city ilike q || '%'))
    order by 7 desc, 6 desc, 2
    limit 30;
end;
$$;

-- Studio → artist: opens (or reuses) the general conversation and sends the first message.
create or replace function public.studio_start_conversation(p_artist_id uuid, p_body text)
returns public.conversations
language plpgsql security definer set search_path = public
as $$
declare
  v_body text := btrim(coalesce(p_body, ''));
  v_studio uuid := (select s.id from public.studios s where s.owner_id = auth.uid() limit 1);
  v_convo uuid;
  v_known boolean;
begin
  if v_studio is null or not public.owns_approved_studio(v_studio) or not public.is_active_user() then
    raise exception 'Only approved studios can message artists.' using errcode = '42501';
  end if;
  if v_body = '' then raise exception 'Write a message first.'; end if;
  if char_length(v_body) > 2000 then raise exception 'Messages can be at most 2000 characters.'; end if;
  if not exists (select 1 from public.profiles p where p.id = p_artist_id and p.role = 'artist' and p.status = 'active') then
    raise exception 'not_found';
  end if;

  v_convo := (select c.id from public.conversations c
              where c.artist_id = p_artist_id and c.studio_id = v_studio and c.booking_id is null);
  if v_convo is null then
    -- Spam protection for cold messages.
    if (select count(*) from public.conversations c
        where c.studio_id = v_studio and c.started_by_studio and c.created_at > now() - interval '1 day') >= 20 then
      raise exception 'You can start 20 new conversations per day. Try again tomorrow.';
    end if;
    -- Artists who already booked or wrote to the studio skip the request step.
    v_known := exists (select 1 from public.bookings b where b.artist_id = p_artist_id and b.studio_id = v_studio)
            or exists (select 1 from public.conversations c where c.artist_id = p_artist_id and c.studio_id = v_studio and not c.started_by_studio);
    v_convo := gen_random_uuid();
    insert into public.conversations (id, artist_id, studio_id, artist_name, studio_name, studio_photo_url, artist_avatar_url, request_status, started_by_studio)
    select v_convo, p_artist_id, s.id,
      coalesce(nullif(a.artist_name, ''), 'Artist'), s.name, s.photo_urls[1], a.avatar_url,
      case when v_known then 'accepted' else 'pending' end, true
    from public.studios s left join public.artist_profiles a on a.id = p_artist_id
    where s.id = v_studio;
  elsif (select c.request_status from public.conversations c where c.id = v_convo) = 'declined' then
    raise exception 'This artist isn''t accepting messages from your studio.';
  end if;

  insert into public.messages (conversation_id, sender_id, kind, body)
  values (v_convo, auth.uid(), 'text', v_body);
  return (select c from public.conversations c where c.id = v_convo);
end;
$$;

-- Artist accepts or declines a message request.
create or replace function public.respond_message_request(p_conversation_id uuid, p_accept boolean)
returns public.conversations
language plpgsql security definer set search_path = public
as $$
begin
  update public.conversations c
  set request_status = case when p_accept then 'accepted' else 'declined' end,
      artist_unread = case when p_accept then c.artist_unread else 0 end
  where c.id = p_conversation_id and c.artist_id = auth.uid();
  if not found then raise exception 'not_found'; end if;
  return (select c from public.conversations c where c.id = p_conversation_id);
end;
$$;

-- Messages: replying accepts a request; requests are announced as such.
create or replace function public.on_message_insert()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  c public.conversations;
  owner uuid;
  from_artist boolean;
begin
  c := (select x from public.conversations x where x.id = new.conversation_id);
  owner := (select s.owner_id from public.studios s where s.id = c.studio_id);
  from_artist := new.sender_id = c.artist_id;

  update public.conversations set
    last_message_preview = left(new.body, 140),
    last_message_at = new.created_at,
    artist_unread = artist_unread + case when new.sender_id is null or not from_artist then 1 else 0 end,
    studio_unread = studio_unread + case when new.sender_id is null or from_artist then 1 else 0 end,
    request_status = case when from_artist then 'accepted' else request_status end
  where id = c.id;

  if new.kind = 'text' and not (not from_artist and c.request_status = 'declined') then
    perform public.notify(
      case when from_artist then owner else c.artist_id end,
      'new_message',
      case
        when from_artist then c.artist_name
        when c.request_status = 'pending' then 'Message request · ' || c.studio_name
        else c.studio_name
      end,
      left(new.body, 140),
      c.booking_id, c.id
    );
  end if;
  return new;
end;
$$;

-- Support ratings ------------------------------------------------------
-- EasySesh: users rate how their support request was handled once it's closed.

alter table public.support_tickets
  add column if not exists rating smallint check (rating between 1 and 5),
  add column if not exists rating_comment text,
  add column if not exists rated_at timestamptz;

-- The ticket owner rates a closed ticket (can change it later).
create or replace function public.rate_support_ticket(p_ticket_id uuid, p_rating integer, p_comment text default null)
returns public.support_tickets
language plpgsql security definer set search_path = public
as $$
declare
  v_status text := (select t.status from public.support_tickets t where t.id = p_ticket_id and t.user_id = auth.uid());
begin
  if v_status is null then raise exception 'not_found'; end if;
  if v_status <> 'closed' then raise exception 'You can rate a request once it is closed.'; end if;
  if p_rating is null or p_rating not between 1 and 5 then raise exception 'Pick 1 to 5 stars.'; end if;
  update public.support_tickets
  set rating = p_rating,
      rating_comment = nullif(left(btrim(coalesce(p_comment, '')), 1000), ''),
      rated_at = now()
  where id = p_ticket_id;
  return (select t from public.support_tickets t where t.id = p_ticket_id);
end;
$$;

-- Admin view keeps its columns in sync with the table (t.* is expanded when the view is created).
drop view if exists public.admin_support_tickets;
drop view if exists public.admin_support_tickets;
create view public.admin_support_tickets with (security_invoker = true) as
select t.*, p.email as user_email, p.role as user_role,
  coalesce(nullif(a.artist_name, ''), nullif(s.name, ''), p.email) as user_name,
  b.reference as booking_reference
from public.support_tickets t
join public.profiles p on p.id = t.user_id
left join public.artist_profiles a on a.id = t.user_id
left join public.studios s on s.owner_id = t.user_id
left join public.bookings b on b.id = t.booking_id;

-- Grants ---------------------------------------------------------------
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant execute on all functions in schema public to authenticated, service_role;
revoke execute on function public.notify, public.booking_system_message, public.call_edge_function,
  public.notify_payment_problem, public.add_support_message from anon, authenticated;
