#!/usr/bin/env python3
"""Builds supabase/updates/latest.sql: everything added since the first setup.sql, for a database
that already ran setup.sql. Idempotent (safe to run again) and keeps all data.
Avoids "select ... into <var>" so the Supabase SQL Editor doesn't mistake it for CREATE TABLE.
Run from the repo root:  python3 supabase/scripts/build_update.py
"""
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
mig = lambda name: open(os.path.join(ROOT, "migrations", name), encoding="utf-8").read()

def idempotent(sql: str) -> str:
    sql = sql.replace("create table public.", "create table if not exists public.")
    sql = re.sub(r"create (unique )?index (?!if not exists)", lambda m: f"create {m.group(1) or ''}index if not exists ", sql)
    sql = re.sub(r'create policy "([^"]+)" on (public\.\w+)',
                 lambda m: f'drop policy if exists "{m.group(1)}" on {m.group(2)};\ncreate policy "{m.group(1)}" on {m.group(2)}', sql)
    sql = sql.replace("drop policy if exists \"messages: participants send\" on public.messages;\ndrop policy if exists",
                      "drop policy if exists")
    sql = re.sub(r"create view (public\.\w+)", r"drop view if exists \1;\ncreate view \1", sql)
    sql = re.sub(r"alter publication supabase_realtime add table (public\.(\w+));",
                 lambda m: f"""do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = '{m.group(2)}') then
    alter publication supabase_realtime add table {m.group(1)};
  end if;
end $$;""", sql)
    return sql

security = mig("20260924000002_security.sql")
guard = security[security.index("create or replace function public.guard_studios()"):security.index("create trigger guard_studios")].rstrip()

parts = [
    """-- =====================================================================
-- EASYSESH database update (for a database that already ran setup.sql)
--  • Fix: "You already have a studio" when saving a studio application again
--  • Contact support (tickets in the app, replies from the admin dashboard)
--  • Message requests (studios can write to artists; artists accept/decline)
--  • Support ratings (users rate closed support requests)
--  • Notification texts say EasySesh
--
-- Supabase → SQL Editor → New query → paste this whole file → Run.
-- Safe to run more than once; keeps all existing data.
-- Generated by supabase/scripts/build_update.py
-- =====================================================================
""",
    "-- Studio save fix ------------------------------------------------------\n" + guard + "\n",
    "-- Support --------------------------------------------------------------\n" + idempotent(mig("20260926000001_support.sql")),
    "-- Message requests -----------------------------------------------------\n"
    # search_artists gets a new return type further down; drop it so running the update again works.
    + "drop function if exists public.search_artists(text);\n" + idempotent(mig("20260927000001_message_requests.sql")),
    "-- Support ratings ------------------------------------------------------\n" + idempotent(mig("20260928000001_support_ratings.sql")),
    "-- Admin badge, admin tags, promotions ----------------------------------\n" + idempotent(mig("20260929000001_badges_tags_promotions.sql")),
    "-- Bookings without edge functions --------------------------------------\n" + idempotent(mig("20260930000001_bookings_in_db.sql")),
    "-- Artist ratings, deleting notifications -------------------------------\n" + idempotent(mig("20261001000001_artist_ratings_notifications.sql")),
    "-- Platform fee enforcement ---------------------------------------------\n" + idempotent(mig("20261002000001_fee_enforcement.sql")),
    "-- Special deals, contact rules, rating disputes ------------------------\n" + idempotent(mig("20261003000001_deals_contact_rating_disputes.sql")),
    "-- Studio <-> artist profile connections --------------------------------\n" + idempotent(mig("20261004000001_studio_artist_links.sql")),
    "-- Booking requests expire after 24 hours -------------------------------\n" + idempotent(mig("20261005000001_request_expiry.sql")),
    "-- Check-in on arrival ---------------------------------------------------\n" + idempotent(mig("20261006000001_check_in.sql")),
    "-- Changelog and terms updates ------------------------------------------\n" + idempotent(mig("20261007000001_changelog_terms_updates.sql")),
    "-- Moderation: warnings, timed suspensions and bans, history ------------\n" + idempotent(mig("20261008000001_moderation.sql")),
    "-- Old scheduled job names (sonora-*) removed ---------------------------\n" + idempotent(mig("20261009000001_rename_cron_jobs.sql")),
    "-- Download my data without edge functions ------------------------------\n" + idempotent(mig("20261010000001_export_my_data.sql")),
    """-- Grants ---------------------------------------------------------------
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant execute on all functions in schema public to authenticated, service_role;
revoke execute on function public.notify, public.booking_system_message, public.call_edge_function,
  public.notify_payment_problem, public.add_support_message, public.activate_promotion,
  public.expire_promotions, public.create_fee_invoices, public.run_fee_enforcement,
  public.refresh_artist_rating from anon, authenticated;
""",
]
out = "\n".join(parts)
bad = [m.group(0) for m in re.finditer(r"(?i)\b(select|returning)\b[^;]*?\binto\s+\w+", out)]
if bad:
    raise SystemExit(f"update contains SELECT/RETURNING INTO, which breaks the SQL Editor: {bad[:3]}")
os.makedirs(os.path.join(ROOT, "updates"), exist_ok=True)
with open(os.path.join(ROOT, "updates", "latest.sql"), "w", encoding="utf-8") as f:
    f.write(out)
print(f"updates/latest.sql: {out.count(chr(10))} lines")
