#!/usr/bin/env python3
"""Builds supabase/setup.sql: every migration in one file that can be pasted into the SQL Editor.

The file starts with a reset block (so it can be re-run safely) and ends with explicit grants.
Run from the repo root:  python3 supabase/scripts/build_setup.py
"""
import glob
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
migrations = sorted(glob.glob(os.path.join(ROOT, "migrations", "*.sql")))
body = {os.path.basename(p): open(p).read() for p in migrations}
all_sql = "\n".join(body.values())

tables = re.findall(r"create table public\.([a-z_]+)", all_sql)
views = re.findall(r"create (?:or replace )?view public\.([a-z_]+)", all_sql)
types = re.findall(r"create type public\.([a-z_]+)", all_sql)
functions = sorted(set(re.findall(r"create or replace function public\.([a-z_]+)", all_sql)))
cron_jobs = re.findall(r"cron\.schedule\('([a-z-]+)'", all_sql)
storage_policies = re.findall(r'create policy "([^"]+)" on storage\.objects', all_sql)

reset = [
    "-- Extensions first (the reset below needs pg_cron).",
    "create extension if not exists pg_cron with schema pg_catalog;",
    "create extension if not exists pg_net with schema extensions;",
    "create extension if not exists btree_gist with schema extensions;",
    "",
    "-- Reset: removes EasySesh objects (and their data) so this file can be run again.",
]
reset.append("drop trigger if exists on_auth_user_created on auth.users;")
for job in cron_jobs:
    reset.append(f"select cron.unschedule('{job}') where exists (select 1 from cron.job where jobname = '{job}');")
for view in views:
    reset.append(f"drop view if exists public.{view} cascade;")
for table in reversed(tables):
    reset.append(f"drop table if exists public.{table} cascade;")
for fn in functions:
    reset.append(f"drop function if exists public.{fn} cascade;")
for t in types:
    reset.append(f"drop type if exists public.{t} cascade;")
for policy in storage_policies:
    reset.append(f'drop policy if exists "{policy}" on storage.objects;')

grants = """
-- ---------------------------------------------------------------------
-- Accounts that already exist in auth (e.g. when re-running this file)
-- get their profile rows back.
-- ---------------------------------------------------------------------
insert into public.profiles (id, email, role)
select u.id, coalesce(u.email, ''),
  case when u.raw_user_meta_data ->> 'role' = 'studio_owner' then 'studio_owner'::public.user_role else 'artist'::public.user_role end
from auth.users u
on conflict (id) do nothing;
insert into public.artist_profiles (id)
select p.id from public.profiles p where p.role = 'artist'
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- Grants: the app signs in as "authenticated". Row-level security above
-- decides which rows each user can see or change.
-- ---------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated, service_role;
grant select on public.platform_settings to anon;
grant execute on all functions in schema public to authenticated, service_role;
revoke execute on function public.notify, public.booking_system_message, public.call_edge_function,
  public.notify_payment_problem, public.add_support_message from anon, authenticated;
"""

out = ["""-- =====================================================================
-- EASYSESH – complete database setup (all migrations in one file)
--
-- 1. Supabase dashboard → SQL Editor → New query
-- 2. Paste this whole file and press Run. It is safe to run again, but
--    running it again deletes all EasySesh data (accounts in auth stay).
-- 3. Then run the two vault lines at the very bottom with your own keys.
--
-- Generated by supabase/scripts/build_setup.py from supabase/migrations.
-- =====================================================================
"""]
out.append("\n".join(reset) + "\n")
for name, sql in body.items():
    out.append(f"\n-- ---------------------------------------------------------------------\n-- {name}\n-- ---------------------------------------------------------------------\n")
    out.append(sql)
out.append(grants)
out.append("""
-- =====================================================================
-- LAST STEP (run separately, with your own values):
-- Lets scheduled jobs and push notifications call the edge functions.
-- Service role key: Project Settings → API Keys → service_role / secret (keep it private).
--
-- select vault.create_secret('https://YOUR-PROJECT-REF.supabase.co', 'project_url');
-- select vault.create_secret('YOUR-SERVICE-ROLE-KEY', 'service_role_key');
-- =====================================================================
""")
with open(os.path.join(ROOT, "setup.sql"), "w") as f:
    f.write("".join(out))
print(f"setup.sql: {len(tables)} tables, {len(views)} views, {len(functions)} functions, {len(types)} types, {len(cron_jobs)} cron jobs")
